development:
  adapter: mysql
  encoding: utf8
  database: dphaener_development
  pool: 5
  username: root
  password: marley12

test:
  adapter: mysql
  encoding: utf8
  database: dphaener_test
  pool: 5
  username: root
  password: marley12

production:
  adapter: mysql
  encoding: utf8
  database: dphaener_production
  pool: 5
  username: root
  password: marley12
