development:
  adapter: postgresql
  encoding: utf8
  database: dphaener_development
  pool: 5
  username: darinhaener
  password: Marley!23

test:
  adapter: postgresql
  encoding: utf8
  database: dphaener_test
  pool: 5
  username: darinhaener
  password: Marley!23
